language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get install python3-setuptools
  - sudo apt-get install python3-pip python3-dev build-essential

install:
  - easy_install .

script:
  - ci/ci_main.sh
